"""Vendored, generated MEXC spot v3 protobuf bindings.

These ``*_pb2.py`` modules are generated by ``protoc`` from the ``.proto`` files
in ``crypto_collector/proto/mexc`` and committed so that **runtime needs only the
``protobuf`` package, never ``protoc``**. Do not edit them by hand - regenerate
with ``scripts/generate_mexc_protobuf.py`` (see ``proto/mexc/README.md``). The
only post-generation edit is rewriting the wrapper's cross-module imports to be
package-relative, which that script performs.
"""
