"""MEXC spot v3 public market-data: protobuf frame decode + subscription helpers.

MEXC retired its JSON websocket (`wss://wbs.mexc.com/ws`) on 2025-08-04. The only
public market-data endpoint now is `wss://wbs-api.mexc.com/ws`, which pushes
**binary Protocol Buffers** frames (the JSON ack / PING-PONG control frames stay
JSON text). This module is the one MEXC-specific seam the rest of the plant needs:
it turns a binary `PushDataV3ApiWrapper` frame into the same kind of plain `dict`
every other (JSON) venue hands the pipeline, so the normalizer / quality gate /
replay / curation chain downstream is unchanged.

Decoding goes through the **official** generated protobuf bindings
(`collectors/mexc_pb/*_pb2.py`, generated by `protoc` from the vendored
`proto/mexc/*.proto` and committed) plus the `protobuf` runtime - we never
hand-parse the wire format. `protoc` itself is only needed at regeneration time
(`scripts/generate_mexc_protobuf.py`), never at runtime.

Provenance: the decoded dict carries a `_mexc_decode` block (schema name, proto
source, decoder version, frame byte length, SHA-256, and base64 of the original
frame). It is written verbatim into `raw/messages.jsonl`, so the raw archive stays
a true rebuild source even though the wire bytes were protobuf - you can re-decode
or re-verify a frame from raw alone.
"""

from __future__ import annotations

import base64
import hashlib
from typing import Any

# Public endpoint (JSON `wbs.mexc.com` was discontinued 2025-08-04; this one is
# protobuf-only). Public market data only - no signed/private streams here.
MEXC_WS_URL = "wss://wbs-api.mexc.com/ws"

# Channel prefixes (the `.pb` protobuf variants). The worker appends the interval
# and/or symbol and/or depth to form the full topic - see the build_* helpers.
MEXC_DEALS_CHANNEL = "spot@public.aggre.deals.v3.api.pb"
MEXC_LIMIT_DEPTH_CHANNEL = "spot@public.limit.depth.v3.api.pb"

# MEXC drops a connection that subscribed but received no data within ~60s and
# documents a client `{"method":"PING"}` heartbeat (server replies {"msg":"PONG"}).
MEXC_PING_MESSAGE: dict[str, str] = {"method": "PING"}
MEXC_PING_INTERVAL_SECONDS = 20.0

# Bumped if the decoded-dict shape this module emits ever changes, so a consumer
# of raw `_mexc_decode` provenance can tell which decoder produced a frame.
DECODER_VERSION = 1
_PROTO_SOURCE = "github.com/mexcdevelop/websocket-proto"
_PROVENANCE_KEY = "_mexc_decode"


def build_deals_topic(*, channel: str, symbol: str, interval: str) -> str:
    """`spot@public.aggre.deals.v3.api.pb@<interval>@<SYMBOL>` (interval e.g. 100ms)."""
    return f"{channel}@{interval}@{symbol.upper()}"


def build_limit_depth_topic(*, channel: str, symbol: str, depth: int) -> str:
    """`spot@public.limit.depth.v3.api.pb@<SYMBOL>@<depth>` (depth e.g. 5/10/20)."""
    return f"{channel}@{symbol.upper()}@{int(depth)}"


def _load_wrapper_cls():
    """Lazily import the generated wrapper message class.

    Kept lazy (and behind a clear error) so importing the CLI never requires
    `protobuf` - only actually running a MEXC worker does. Mirrors the
    `import websockets` guard the live collectors already use.
    """
    try:
        from .mexc_pb import PushDataV3ApiWrapper_pb2  # noqa: PLC0415
    except ImportError as exc:  # pragma: no cover - exercised only without protobuf
        raise RuntimeError(
            "MEXC market data is protobuf-encoded; install the 'protobuf' runtime "
            "(pip install -e \".[mexc]\") to run a MEXC worker. The generated "
            "bindings live in crypto_collector.collectors.mexc_pb."
        ) from exc
    return PushDataV3ApiWrapper_pb2.PushDataV3ApiWrapper


def decode_mexc_frame(data: bytes) -> dict[str, Any]:
    """Decode one binary `PushDataV3ApiWrapper` frame into a plain dict.

    The dict mirrors the protobuf field names (`channel`, `symbol`, `sendTime`,
    `createTime`, and exactly one body of `publicAggreDeals` / `publicLimitDepths`)
    and carries a `_mexc_decode` provenance block. int64 fields (`sendTime`,
    `createTime`, deal `time`) come back as decimal strings per proto3 JSON
    mapping; the normalizers parse them. Returns the same shape regardless of
    body so `_should_emit` / the normalizers can branch on which body is present.
    """
    from google.protobuf.json_format import MessageToDict  # noqa: PLC0415

    wrapper_cls = _load_wrapper_cls()
    message = wrapper_cls.FromString(bytes(data))
    decoded: dict[str, Any] = MessageToDict(message, preserving_proto_field_name=True)
    decoded[_PROVENANCE_KEY] = {
        "schema": "PushDataV3ApiWrapper",
        "proto_source": _PROTO_SOURCE,
        "decoder_version": DECODER_VERSION,
        "frame_bytes": len(data),
        "frame_sha256": hashlib.sha256(bytes(data)).hexdigest(),
        # base64 of the original wire frame keeps raw a true rebuild source even
        # though the archived payload is the decoded form (protobuf isn't JSON).
        "frame_b64": base64.b64encode(bytes(data)).decode("ascii"),
    }
    return decoded
